// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDunRrtpl3V0x3CsOmR4RvPCC2eBPBOeUs',
    appId: '1:493641618614:web:5034f745246096074e0217',
    messagingSenderId: '493641618614',
    projectId: 'final-year-project-9620e',
    authDomain: 'final-year-project-9620e.firebaseapp.com',
    databaseURL: 'https://final-year-project-9620e-default-rtdb.firebaseio.com',
    storageBucket: 'final-year-project-9620e.firebasestorage.app',
    measurementId: 'G-7JL05PGENG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUS4Yh8X-UAgnWLYpxRAJTk2niU9BbEcc',
    appId: '1:493641618614:android:73b00518f9ea4a084e0217',
    messagingSenderId: '493641618614',
    projectId: 'final-year-project-9620e',
    databaseURL: 'https://final-year-project-9620e-default-rtdb.firebaseio.com',
    storageBucket: 'final-year-project-9620e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5k36vXh66R-1YoJFJvrNkv89FtJCs4O8',
    appId: '1:493641618614:ios:8f98d9bd28e550054e0217',
    messagingSenderId: '493641618614',
    projectId: 'final-year-project-9620e',
    databaseURL: 'https://final-year-project-9620e-default-rtdb.firebaseio.com',
    storageBucket: 'final-year-project-9620e.firebasestorage.app',
    iosBundleId: 'com.example.globalshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDunRrtpl3V0x3CsOmR4RvPCC2eBPBOeUs',
    appId: '1:493641618614:web:ecf5cd06ea10684a4e0217',
    messagingSenderId: '493641618614',
    projectId: 'final-year-project-9620e',
    authDomain: 'final-year-project-9620e.firebaseapp.com',
    databaseURL: 'https://final-year-project-9620e-default-rtdb.firebaseio.com',
    storageBucket: 'final-year-project-9620e.firebasestorage.app',
    measurementId: 'G-ZVLLWSHG6X',
  );
}
